-- La Perdrix — group holiday planner & spend tracker
-- Run once in the Supabase SQL editor (Dashboard → SQL Editor → New query).
--
-- DESIGN NOTE, and it drives everything below:
-- This is a spend *tracker*, not an accounting tool. People make themselves a
-- profile (a name and a rustic icon), log what they spent, and the group keeps a
-- loose eye on the balance. It never tells anyone they owe anyone money.
--
-- Therefore THE PERSON IS THE ATOM. Households exist only as an optional label
-- for grouping totals — they are not the unit splitting is built on. This is what
-- lets the app cope with anything from 3 to 12 households, and with the very
-- different shapes real groups have (couples, singles, families with toddlers).
--
-- Money is numeric(12,2) throughout — never float. FX rates are numeric(12,6).
--
-- FX CONVENTION: fx_rate is "units of home_currency per 1 unit of local_currency".
--   local EUR, home GBP, fx_rate 0.8500  →  amount_home = amount_local * 0.85
-- amount_home is computed at save time and stored, so later rate changes never
-- silently rewrite history.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- enums

do $$ begin
  create type expense_phase as enum ('pre_trip', 'on_trip');
exception when duplicate_object then null; end $$;

-- 'none' = don't compute fair shares at all, just show who paid what.
-- The honest default for a group that doesn't want to be audited.
do $$ begin
  create type split_basis as enum ('per_person', 'per_household', 'none');
exception when duplicate_object then null; end $$;

-- NOTE: itinerary_kind is deliberately NOT declared here — the calendar work owns
-- the itinerary. See the ownership note further down.

-- ---------------------------------------------------------------- trips

create table if not exists trips (
  id                  uuid primary key default gen_random_uuid(),
  name                text not null,
  destination         text,
  -- Full postal address and owner contacts: what you actually need on your phone
  -- at 11pm on arrival day when you cannot find the gate.
  address             text,
  contacts            text,
  start_date          date,
  end_date            date,
  home_currency       char(3) not null default 'GBP',
  local_currency      char(3) not null default 'EUR',
  fx_rate             numeric(12,6),
  fx_rate_source      text,
  fx_rate_updated_at  timestamptz,
  split_basis         split_basis not null default 'per_person',
  -- Optional hero image for the Home tab (Supabase Storage key). Turns the app
  -- from a spreadsheet into a keepsake.
  hero_path           text,
  -- The share link is the password. High-entropy, generated by the Worker.
  access_token        text not null unique,
  created_at          timestamptz not null default now()
);

-- ---------------------------------------------------------------- households (optional)

-- Purely a grouping label — "the Marshes", "Cluny Cottage". A person need not
-- belong to one, and nothing breaks if nobody uses them.
create table if not exists households (
  id          uuid primary key default gen_random_uuid(),
  trip_id     uuid not null references trips(id) on delete cascade,
  name        text not null,
  sort_order  int not null default 0
);
create index if not exists households_trip_idx on households (trip_id, sort_order);

-- ---------------------------------------------------------------- people

-- Self-created: you open the share link, type your name, pick a rustic icon,
-- and you exist. No admin sets these up in advance.
create table if not exists members (
  id            uuid primary key default gen_random_uuid(),
  trip_id       uuid not null references trips(id) on delete cascade,
  household_id  uuid references households(id) on delete set null,
  name          text not null,
  -- Icon slug from the app's rustic set: 'partridge', 'chicken', 'cheese',
  -- 'wine', 'dog', 'fig', 'walnut', 'olive', 'bread', 'tomato', 'sunflower',
  -- 'hat', 'boules', 'swim', 'hammock', 'steeple', 'snail', 'goat'.
  icon          text not null default 'partridge',
  colour        text,
  -- Counts toward per-person fair share. Set false for babies, or for someone
  -- who's only there for a weekend, without deleting them.
  counts_in_share boolean not null default true,
  -- When this person is actually there. NULL = the whole trip.
  -- In a group this size people trickle in and out across a fortnight, so the
  -- landing page draws a presence chart from these two columns — it answers
  -- "who's around on Thursday?" without anyone having to ask in the group chat.
  arrives_on    date,
  departs_on    date,
  sort_order    int not null default 0,
  created_at    timestamptz not null default now(),
  constraint members_stay_ordered check (
    arrives_on is null or departs_on is null or departs_on >= arrives_on
  )
);
create index if not exists members_trip_idx on members (trip_id, sort_order);
-- Two people can share a name in a group of 27; the icon disambiguates. But the
-- same name AND icon twice is almost certainly a double-tap on the create button.
create unique index if not exists members_trip_name_icon_uniq
  on members (trip_id, lower(name), icon);

-- ---------------------------------------------------------------- expenses

-- ONE ledger for the whole trip. The pre-trip budget is not a separate
-- subsystem, just rows with phase = 'pre_trip'.
create table if not exists expenses (
  id                      uuid primary key default gen_random_uuid(),
  trip_id                 uuid not null references trips(id) on delete cascade,
  description             text,
  merchant                text,
  category                text,
  spent_on                date not null default current_date,
  note                    text,
  phase                   expense_phase not null default 'on_trip',

  paid_by_member_id       uuid references members(id) on delete set null,
  created_by_member_id    uuid references members(id) on delete set null,

  amount_local            numeric(12,2) not null,
  currency                char(3) not null,
  amount_home             numeric(12,2) not null,
  fx_rate_used            numeric(12,6),

  -- The whole of the loose splitting model: NULL means "everyone".
  -- Tick specific people only when a cost genuinely wasn't for the whole group.
  -- Person-level rather than household-level because that's strictly more
  -- flexible: the UI offers "select whole household" as a shortcut.
  beneficiary_member_ids  uuid[],

  receipt_path            text,

  -- Idempotency key generated on the client BEFORE the first send attempt.
  -- The offline queue retries; without this, a retry that actually succeeded
  -- the first time would silently create a duplicate expense.
  client_id               text unique,

  created_at              timestamptz not null default now()
);
create index if not exists expenses_trip_date_idx on expenses (trip_id, spent_on desc);
create index if not exists expenses_trip_phase_idx on expenses (trip_id, phase);
create index if not exists expenses_payer_idx on expenses (paid_by_member_id);

-- ---------------------------------------------------------------- extractions

-- Audit trail: what the model read versus what the human saved. This is how we
-- find out whether extraction is any good, and how the prompt gets improved.
create table if not exists extractions (
  id              uuid primary key default gen_random_uuid(),
  trip_id         uuid references trips(id) on delete cascade,
  expense_id      uuid references expenses(id) on delete set null,
  model           text,
  raw_response    jsonb,
  confidence      numeric(4,3),
  user_corrected  boolean not null default false,
  created_at      timestamptz not null default now()
);
create index if not exists extractions_trip_idx on extractions (trip_id, created_at desc);

-- ---------------------------------------------------------------- itinerary
--
--   *** NOT DEFINED HERE. The calendar work owns it. ***
--
-- Ownership split agreed with Ed: the calendar work owns itinerary and attendance
-- DATA and LOGIC; this file and the landing page own PRESENTATION. Whatever shape
-- the calendar side settles on, the landing page reads it through the two views
-- below and nothing else. That is the whole integration surface — keep it small.
--
-- Define itinerary tables in a separate file so the two of us never clobber each
-- other's migrations, then expose these:
--
--   create view trip_days as
--     select trip_id, day, title, detail, kind, household_id, start_time, sort_order ...
--
--   create view member_presence as
--     select member_id, trip_id, arrives_on, departs_on ...
--
-- `member_presence` is what the presence chart on the landing page draws. It
-- currently falls out of members.arrives_on / members.departs_on below, but if the
-- calendar work models attendance some richer way (multiple stays per person, say),
-- point the view at that instead and the chart keeps working untouched.

-- ---------------------------------------------------------------- security

-- Every table here is reached ONLY through the Cloudflare Worker using the
-- service-role key, which bypasses RLS. Enabling RLS with no policies therefore
-- denies the anon and authenticated roles completely — exactly what we want,
-- since the browser never talks to Supabase directly.
alter table trips            enable row level security;
alter table households       enable row level security;
alter table members          enable row level security;
alter table expenses         enable row level security;
alter table extractions      enable row level security;
-- The calendar work must do the same for its own tables.

-- ---------------------------------------------------------------- storage

-- Private buckets. Receipts can carry card digits and names, so this must never
-- be public; the Worker issues short-lived signed URLs.
insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('trip-photos', 'trip-photos', false)
on conflict (id) do nothing;
