#!/usr/bin/env python3
"""Generate photos.css — tiny blurred stand-ins for each photograph.

Once the photographs live in a private bucket, the page cannot show them until
JavaScript has fetched signed URLs. Without something in their place the hero is
a black rectangle on first paint, which on a bad Dordogne line could be several
seconds. These are 16px-wide JPEGs inlined as data URIs: a few hundred bytes
each, stretched to full size by background-size:cover, so you get the right
colours and shapes immediately and the real photograph replaces them.

Run from the repo root:  python3 scripts/gen_placeholders.py
"""
import base64, pathlib, subprocess, sys, tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "photos"
OUT = ROOT / "photos.css"
NAMES = ["group", "lake", "abbey", "chair", "mirror", "heads", "hens", "table", "window"]

if not SRC.is_dir():
    sys.exit(f"no {SRC} — the full-size photographs must be present to shrink them")

lines = [
    "/* GENERATED by scripts/gen_placeholders.py — do not edit by hand.",
    " * 16px stand-ins shown until the real photographs arrive from the Worker.",
    " * Overridden at runtime by --ph-* custom properties set in index.html. */",
    ":root{",
]

total = 0
with tempfile.TemporaryDirectory() as tmp:
    for name in NAMES:
        src = SRC / f"{name}.jpg"
        if not src.exists():
            sys.exit(f"missing {src}")
        tiny = pathlib.Path(tmp) / f"{name}.jpg"
        subprocess.run(
            ["sips", "-Z", "16", "-s", "format", "jpeg", "-s", "formatOptions", "40",
             str(src), "--out", str(tiny)],
            check=True, capture_output=True,
        )
        b64 = base64.b64encode(tiny.read_bytes()).decode()
        total += len(b64)
        lines.append(f'  --ph-{name}:url("data:image/jpeg;base64,{b64}");')

lines.append("}")
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.name}: {len(NAMES)} placeholders, {round(total/1024, 1)} KB of base64 total")
